stages:
  - warning
  - ok_to_submit
  - test
  - grade

build-job:
  stage: warning
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "$CI_PROJECT_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
