stages:
  - grade

grade:
  stage: grade
  image: $TESTING_DOCKER_IMAGE
  script:
    - echo $CI_PROJECT_NAME
    - git clone $PRIVATE_TEST_REPO
    - python3 gradepy/grade.py --grade --pa $PA --user $CI_PROJECT_NAME --commit $COMMIT
  rules:
    - if: $CI_PIPELINE_SOURCE == "api"
    - if: 
  artifacts:
    paths: 
      - pa${PA}/PA${PA}_grade.txt
      - pa${PA}/PA${PA}_debug.txt