stages:
  - grade

build-job:
  stage: grade
  image: $TESTING_DOCKER_IMAGE
  script:
    - echo $CI_PROJECT_NAME
    - git clone $PRIVATE_TEST_REPO
    - cd pa{$PA}
    - python3 ../gradepy/grade.py --grade --pa $PA -v debug --user $CI_PROJECT_NAME --commit $CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "api"
  artifacts:
    paths: 
      - ${PA}_grade.txt
      - ${PA}_debug.txt